nome = input('Digite seu nome completo: ')
caixaAlta = nome.upper()
caixaBaixa = nome.lower()
qtdLetras = len(nome.replace(' ',''))
letrasPrimeiroNome = len(nome.split()[0])
print('O seu nome completo em letras maisculas é {}'.format(caixaAlta))
print('O seu nome completo em letras minusculas é {}'.format(caixaBaixa))
print('O seu nome possui {} letras desconsiderando o espaçamento!'.format(qtdLetras))
print('O seu primeiro nome possui {} letras!'.format(letrasPrimeiroNome))
